name : Tf Jobs

on :
  pull_request:
    branches:
      - main 

jobs:
  terraform-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - name: Terraform format
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Tf Validate 
        id: vld
        run: terraform validate -no-color 
    
